#######################################################################
# WEB PUBLIC OPTIONS                                                  #
#######################################################################

WebPublic:
    DomainName: lvh.me
    HttpPort: 80
    HttpIp: 123.45.6.7
    Https:
        Enabled: false
        Port: 443
        Ip: 123.45.6.7

        # Provider to use, possible values: custom, letsencrypt
        Provider: letsencrypt

        # ++++++ For letsencrypt only ++++++
        SubscriberEmail: info@lvh.me
        CertFolder: ssl

        # ++++++ For custom only ++++++
        CertPemFileName: ssl/cert.pem
        KeyPemFileName: ssl/key.pem

#######################################################################
# WEB PAGES OPTIONS                                                   #
#######################################################################

WebPagesFolder: pages
JsSettingsPath: /js/_settings.js

#######################################################################
# COMMAND OPTIONS                                                     #
#######################################################################

CommandPathPrefix: /cmd/
ParametersCountLimit: 30
CommandParametersFileName: command_parameters.json

#######################################################################
# OAUTH OPTIONS                                                       #
#######################################################################

OAuthVerificationCodePath: /cmd/oauth_verification_code
OAuthYandex:
    ClientId: aaa
    ClientSecret: bbb
OAuthGoogle:
    ClientId: ccc
    ClientSecret: ddd
OAuthGitHub:
    ClientId: eee
    ClientSecret: fff

#######################################################################
# DATABASE OPTIONS                                                    #
#######################################################################

DbConnectionString: sqlserver://user:pawword@localhost?database=test&connection+timeout=30
